GRABAR TFG/Herramienta Web (Código Fuente)/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root    'static_pages#home'

  get 'help'  =>  'static_pages#help'

  get 'about' =>  'static_pages#about'

  get 'maps'  =>  'static_pages#maps'

  get 'contact' => 'contact_us/contacts#new'

  get 'coords' => 'static_pages#coords'

  get 'car' => 'static_pages#car'

  get 'editCar' => 'static_pages#editCar'

  get 'newCar' => 'static_pages#newCar'

  get 'deleteCar' =>  'static_pages#deleteCar'

end

GRABAR TFG/Herramienta Web (Código Fuente)/app/views/contact_us/contacts/new.html.erb
<div class="jumbotron fixed-top">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Contáctenos</h3>
    </div>
    <div class="panel-body">
      <%= form_for @contact, :url => contacts_path, :html => {:class => 'formtastic'} do |f| %>
      <% if ContactUs.require_name %>
      <div class='string required' id='contact_us_contact_name_input'>
        <%= f.label :name, (t('.name') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
        <%= f.text_field :name%>
        <% if f.object.errors[:name].present? %>
        <p class='inline-error'><%= f.object.errors[:name].join(' and ') %></p>
        <% end %>
      </div>
      <% end %>
      <div class='string required' id='contact_us_contact_email_input'>
        <%# <%= f.label :email, (t('.email') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
        <%= f.text_field :email, placeholder: "Email de contacto", :style => "width:40%;" %>
        <% if f.object.errors[:email].present? %>
        <p class='inline-error'><%= f.object.errors[:email].join(' and ') %></p>
        <% end %>
      </div>
      <% if ContactUs.require_subject %>
      <div class='string required' id='contact_us_contact_subject_input'>
        <%= f.label :subject, (t('.subject') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
        <%= f.text_field :subject%>
        <% if f.object.errors[:subject].present? %>
        <p class='inline-error'><%= f.object.errors[:subject].join(' and ') %></p>
        <% end %>
      </div>
      <% end %>
      <div class='text required' id='contact_us_contact_message_input' style="margin-top: 10px;">
        <%# <%= f.label :message, (t('.message') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
        <%= f.text_area :message, placeholder: "Escribe aquí tu comentario", :style => "width:100%; height: 100px;" %>
        <% if f.object.errors[:message].present? %>
        <p class='inline-error'><%= f.object.errors[:message].join(' y ') %></p>
        <% end %>
      </div>
      <div class='commit'>
        <%= f.submit "Enviar", :class => 'submit create btn btn-default', :title => t('.submit'), disabled: true %>
      </div>
      <% end %>
    </div>
  </div>
</div>

GRABAR TFG/Herramienta Web (Código Fuente)/app/views/contact_us/contacts/new_formtastic.html.erb
<h2><%= t('.contact_us') %></h2>
<%= semantic_form_for @contact, :url => contacts_path do |f| %>
  <%= f.input :name, :label => t('.name') if ContactUs.require_name %>
  <%= f.input :email, :label => t('.email') %>
  <%= f.input :subject, :label => t('.subject') if ContactUs.require_subject %>
  <%= f.input :message, :as => :text, :label => t('.message') %>
  <%= f.action :submit, :label => t('.submit'), :button_html => { :alt => t('.submit'), :id => 'contact_us_contact_submit', :title => t('.submit') } %>
<% end %>

GRABAR TFG/Herramienta Web (Código Fuente)/app/views/contact_us/contacts/new_simple_form.html.erb
<h2><%= t('.contact_us') %></h2>
<%= simple_form_for @contact, :url => contacts_path do |f| %>
  <%= f.input :name, :label => t('.name') if ContactUs.require_name %>
  <%= f.input :email, :label => t('.email') %>
  <%= f.input :subject, :label => t('.subject') if ContactUs.require_subject %>
  <%= f.input :message, :as => :text, :label => t('.message') %>
  <%= f.button :submit, :value => t('.submit'), :alt => t('.submit'), :id => 'contact_us_contact_submit', :title => t('.submit') %>
<% end %>