GRABAR TFG/Herramienta Web (Código Fuente)/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root    'static_pages#home'

  get 'help'  =>  'static_pages#help'

  get 'about' =>  'static_pages#about'

  get 'maps'  =>  'static_pages#maps'

  get 'contact' => 'contact_us/contacts#new'

  get 'coords' => 'static_pages#coords'

  get 'car' => 'static_pages#car'

  get 'editCar' => 'static_pages#editCar'

  get 'newCar' => 'static_pages#newCar'

  get 'deleteCar' =>  'static_pages#deleteCar'

end

GRABAR TFG/Herramienta Web (Código Fuente)/app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom navbar-default">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#footer-collapse" aria-expanded="false"><span class="fa fa-chevron-circle-up" style ="color: white"></span>
      <span class="sr-only">Toggle navigation</span>
<!--       <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span> -->
    </button>
	<nav>
	<div class="collapse navbar-collapse" id="footer-collapse">
		<ul class="nav navbar-nav navbar-right">
			<li class="<%= 'active' if current_page?(contact_path) %>">
				<%= link_to contact_path do %>
				<i class="fa fa-envelope" style="margin-right: 10px"></i>Contacto
				<% end %>
			</li>
			<li class="<%= 'active' if current_page?(about_path) %>">
				<%= link_to about_path do %>
				<i class="fa fa-info-circle" style="margin-right: 10px"></i>Acerca de
				<% end %>
			</li>
			<li class="<%= 'active' if current_page?(help_path) %>">
				<%= link_to help_path do %>
				<i class="fa fa-question-circle" style="margin-right: 10px"></i>Ayuda
				<% end %>
			</li>
		</ul>
		</div>
	</nav>
</footer>

GRABAR TFG/Herramienta Web (Código Fuente)/app/views/layouts/_header.html.erb
    <!-- Include all compiled plugins (below), or include individual files as needed -->
<header class="navbar navbar-fixed-top navbar-default">
 <!--<nav class="navbar navbar-default">
 <div class="container-fluid">-->
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-collapse" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="brand" href="/">
      <img class="logo" alt="Memento Parking" src="/assets/logo.png">
    </a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="header-collapse">
    <ul class="nav navbar-nav navbar-left">
      <li class="<%= 'active' if current_page?(root_path) %>">
        <%= link_to root_path do %>
        <i class="fa fa-home" style="margin-right: 10px"></i>Inicio
        <% end %>
      </li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <!-- Si el usuario tiene sesión abierta -->
      <% if user_signed_in? %>
      <li style="color:white; padding-top: 20px;">Bienvenido, </li>
      <li>
        <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="margin-top: 7px; margin-left: 10px;"> <span class="glyphicon glyphicon-user" aria-hidden="true" style="margin-right: 10px"></span>
            <%= if !current_user.name then 
              current_user.email 
            elsif current_user.surname then 
              current_user.name + " " + current_user.surname
            else
              current_user.name
              end %> 
              <span class="caret"></span> </button>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to maps_path do %>
                  <i class="fa fa-map-marker" style="margin-right: 10px"></i>Mis ubicaciones
                  <% end %>
                </li>

                <li>
                  <%= link_to edit_user_registration_path do %>
                  <i class="glyphicon glyphicon-edit" style="margin-right: 10px"></i>Mis datos
                  <% end %>
                </li>
                <li>
                  <%= link_to car_path do %>
                  <i class="fa fa-car" style="margin-right: 10px"></i>Mis coches
                  <% end %>
                </li>

                <li role="separator" class="divider"></li>

                <li>
                  <%= link_to destroy_user_session_path, {:class => "label label-danger", :style=>"color:white;"} do %>
                  <i class="fa fa-sign-out" style="margin-right: 10px"></i>Cerrar sesión
                  <% end %>
                </li>


              </ul>
            </div>
          </li>

          <!-- Si el usuario NO tiene sesión abierta -->
          <% else %>
          <li class="<%= 'active' if current_page?(new_user_session_path) %>">
            <%= link_to new_user_session_path do %>
            <i class="fa fa-sign-in" style="margin-right: 10px"></i>Acceder
            <% end %>
          </li>
          <li class="<%= 'active' if current_page?(new_user_registration_path) %>">
            <%= link_to new_user_registration_path do %>
            <i class="fa fa-plus-square" style="margin-right: 10px"></i>Registrarse
            <% end %>
          </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
  <!-- </div>/.container-fluid 
</nav>-->
</header>

GRABAR TFG/Herramienta Web (Código Fuente)/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
<![endif]-->

GRABAR TFG/Herramienta Web (Código Fuente)/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>MementoParking | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAVdlyqpDfn1sXmYcY9WJS4cfU0jnkIWao"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true  %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body style="padding-top = 70px">
	<%= render 'layouts/header' %>
	<div class="container">
	    <%= flash_messages %>
	    <%= yield %>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>